font_family MonoLisa
bold_italic_font auto
font_size 15.0

enabled_layouts splits:split_axis=horizontal

map cmd+right next_tab
map cmd+left previous_tab

map ctrl+alt+t goto_layout tall
map ctrl+alt+s goto_layout stack

map shift+up neighboring_window up
map shift+down neighboring_window down
map shift+left neighboring_window left
map shift+right neighboring_window right


map ctrl+alt+up move_window up
map ctrl+alt+left move_window left
map ctrl+alt+right move_window right
map ctrl+alt+down move_window down

map F5 launch --location=hsplit
map F6 launch --location=vsplit
map F7 layout_action rotate

#startup_session ~/.config/kitty/startup_deewee.conf

force_ltr no
adjust_line_height 0
adjust_column_width 0
disable_ligatures never

cursor #b58900
cursor_text_color #cb4b16
cursor_shape block
cursor_blink_interval 0

mouse_hide_wait 0
focus_follow_mouse yes
default_pointer_shape arrow
pointer_shape_when_dragging beam
enable_audio_bell no
macos_option_as_alt left

remember_window_size no
resize_draw_strategy blank
hide_window_decorations titlebar-only 
resize_in_steps yes

window_border_width 15
window_padding_width 10
active_border_color #9b8364
inactive_border_color #d2b48c
window_margin_width 5
draw_minimal_borders no
initial_window_width 1700
initial_window_height 1100

background_opacity 0.75
foreground            #faf9f6
background            #251607
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #97979B
cursor_text_color     #282A36

allow_remote_control yes

include ./themes/Ciapre.conf
